/*
This package performs reconciliation for a Nuxeo custom resource and the objects that are generated by the Operator
from the CR: Deployment, Ingress/Route, Service, ServiceAccount.

Unit testing is performed using https://github.com/stretchr/testify. See the Make file for the unit test target.

Each unit test file follows the same structure:
  test functions - test functions are at the top, and take a test suite struct receiver
  suite struct - the test suite structure required by testify, and augmented with suite-specific state
  setup/teardown function(s) - perform setup / teardown
  suite function - is run by 'go test' and calls all test functions
  helper functions - called by the various test functions
*/
package nuxeo
