apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: nuxeo-kafka-user
  labels:
    strimzi.io/cluster: strimzi
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
    - resource:
        type: topic
        name: "*"
        patternType: literal
      operation: All
      host: "*"
    - resource:
        type: group
        name: "*"
        patternType: literal
      operation: All
      host: "*"
