apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml
- service_account.yaml

images:
- name: controller
  newName: docker.io/appzygy/nuxeo-operator
  newTag: 0.6.2
