#!/usr/bin/env bash
#
# adapted from: https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-users-and-roles.html
#

BASE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Generate the credentials using the elasticsearch-users CLI tool
mkdir -p "$BASE/scratch"
truncate -s0 "$BASE/scratch/users" "$BASE/scratch/users_roles"
if ! docker run -v "$BASE/scratch:/usr/share/elasticsearch/config" \
  docker.elastic.co/elasticsearch/elasticsearch:6.8.8 \
  bin/elasticsearch-users useradd nxelastic -p nxelasticpass -r superuser; then
  echo FAIL
  exit 1
fi
# create a secret manifest for ElasticSearch from the generated credentials
users=$(cat "$BASE/scratch/users")
users_roles=$(cat "$BASE/scratch/users_roles")
if [[ "$users" == "" ]] || [[ "$users_roles" == "" ]]; then
  echo FAIL
  exit 1
fi
sed "$BASE/stacks/elastic-filerealm/filerealm-secret-template.yaml"\
  -e "s|USERS|$users|" -e "s|ROLES|$users_roles|"\
  >| "$BASE/stacks/elastic-filerealm/filerealm-secret.yaml" && echo PASS || echo FAIL
