#!/usr/bin/env bash
#
# Verifies that Nuxeo started successfully. The tests have NOP readiness and liveness probes in the Nuxeo CR
# because that supports troubleshooting. This script is used to verify that Nuxeo had a clean start. All
# these tests were performed with a Nuxeo image that installs 29 hotfixes on startup, which takes a bit of time.
#

max=20
for ((i=0; i<$max; i++)); do
  if kubectl wait pod -l app=nuxeo -n backing --for condition=ready --timeout=1s &>/dev/null; then
    [[ "$(curl -s -o /dev/null -w '%{http_code}' http://nuxeo-server.apps-crc.testing)" == "200" ]] && break
  fi
  sleep 6s
done
if [[ $i -ge $max ]]; then
  echo FAIL
  exit 1
else
  kubectl get po -l app=nuxeo -n backing -o name | xargs kubectl -n backing logs |\
    grep 'Component Loading Status: Pending: 0 / Missing: 0 / Unstarted: 0' &>/dev/null
  if [[ $? -eq 0 ]]; then
    echo PASS
    exit 0
  else
    echo FAIL
    exit 1
  fi
fi
