    nuxeoConfig:
      jvmPKISecret: foo # contains Key Store + pass + type, Trust Store + pass + type
    marketplacePackages:
    - valueFrom:
        configMap: nuxeo-sample

 
 
 
 
 
 
 
 
 
 
 
 
 

