apiVersion: nuxeo.com/v1alpha1
kind: Nuxeo
metadata:
  name: my-nuxeo
spec:
  nuxeoImage: image-registry.openshift-image-registry.svc.cluster.local:5000/images/nuxeo:10.10
  access:
    hostname: nuxeo-server.apps-crc.testing
  nodeSets:
  - name: cluster
    replicas: 1
    clusterEnabled: true
    interactive: true
    nuxeoConfig:
      nuxeoPackages:
      - nuxeo-web-ui
      nuxeoName: "nuxeo-test"
    storage:
      - storageType: Binaries
        size: 1M
        volumeSource:
          emptyDir: {}