apiVersion: appzygy.net/v1alpha1
kind: Nuxeo
metadata:
  name: my-nuxeo
spec:
  nuxeoImage: nuxeo:LTS-2019
  access:
    hostname: nuxeo-server.apps-crc.testing
    termination: edge
    tlsSecret: tls-secret
  nodeSets:
  - name: cluster
    replicas: 1
    interactive: true
    env:
      - name: NUXEO_PACKAGES
        value: nuxeo-web-ui
