apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "appzygy.net/v1alpha1",
          "kind": "Nuxeo",
          "metadata": {
            "name": "nuxeo-sample"
          },
          "spec": {
            "access": {
              "hostname": "nuxeo-server.apps-crc.testing"
            },
            "nodeSets": [
              {
                "interactive": true,
                "name": "cluster",
                "nuxeoConfig": {
                  "nuxeoPackages": [
                    "nuxeo-web-ui"
                  ]
                },
                "replicas": 1
              }
            ],
            "nuxeoImage": "nuxeo:LTS-2019",
            "version": "10.10"
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.0.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: nuxeo-operator.v0.6.2
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Nuxeo
      name: nuxeos.appzygy.net
      version: v1alpha1
  description: Manages Nuxeo clusters in Kubernetes and OpenShift, and integrates Nuxeo with backing services like Kafka, etc.
  displayName: Nuxeo Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - appzygy.net
          resources:
          - nuxeos
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - appzygy.net
          resources:
          - nuxeos/status
          - nuxeos/finalizers
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          - serviceaccounts
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          - routes/custom-host
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - extensions
          resources:
          - ingresses
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - networking.k8s.io
          resources:
          - ingresses
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: nuxeo-operator-manager
      deployments:
      - name: nuxeo-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: nuxeo-operator
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                app: nuxeo-operator
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --metrics-addr=127.0.0.1:8080
                - --enable-leader-election
                command:
                - /manager
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                image: docker.io/appzygy/nuxeo-operator:0.6.2
                name: manager
                resources:
                  limits:
                    cpu: 100m
                    memory: 300Mi
                  requests:
                    cpu: 100m
                    memory: 300Mi
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              serviceAccountName: nuxeo-operator-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - configmaps/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: nuxeo-operator-manager
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - nuxeo
  - digital
  - asset
  - management
  - golang
  links:
  - name: Nuxeo Operator
    url: https://github.com/aceeric/nuxeo-operator
  maturity: alpha
  provider:
    name: Eric Ace
  version: 0.6.2
