apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app: nuxeo-operator
  name: nuxeo-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
