apiVersion: nuxeo.com/v1alpha1
kind: Nuxeo
metadata:
  name: my-nuxeo
spec:
  nuxeoImage: nuxeo:10.10
  revProxy:
    nginx:
      configMap: tls-cfgmap
      secret: tls-secret
      image: image-registry.openshift-image-registry.svc.cluster.local:5000/nuxeo/nginx:latest
  access:
    hostname: nuxeo-server.apps-crc.testing
    termination: passthrough
  nodeSets:
  - name: cluster
    replicas: 1
    interactive: true
    env:
      - name: NUXEO_PACKAGES
        value: nuxeo-web-ui
