#
# This file is a copy of:
# https://github.com/nuxeo/nuxeo-apb-catalog/blob/master/nuxeo-apb/files/nginx.conf
# todo-me re https://doc.nuxeo.com/nxdoc/http-and-https-reverse-proxy-configuration/#ngnix-issue should this specify 'ignore_invalid_headers off'?
# todo-me can this be automatically provided by the operator if not explicitly overridden since it refs things also ref'd in the Go code
apiVersion: v1
kind: ConfigMap
metadata:
  name: tls-cfgmap
data:
  nginx.conf: |
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/cache/nginx/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        default_type  application/octet-stream;
        log_format json_combined escape=json
          '{'
            '"time_local":"$time_local",'
            '"remote_addr":"$remote_addr",'
            '"remote_user":"$remote_user",'
            '"request":"$request",'
            '"status": "$status",'
            '"body_bytes_sent":"$body_bytes_sent",'
            '"request_time":"$request_time",'
            '"http_referrer":"$http_referer",'
            '"http_user_agent":"$http_user_agent"'
          '}';

        access_log  /var/log/nginx/access.log  json_combined;

        proxy_cache_path        /var/cache/nginx levels=1:2 keys_zone=one:8m max_size=3000m inactive=600m;
        proxy_temp_path         /var/tmp;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        gzip                    on;
        gzip_comp_level         6;
        gzip_vary               on;
        gzip_min_length         1000;
        gzip_proxied            any;
        gzip_types              text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
        gzip_buffers 16 8k;

        client_max_body_size 20M;
        include /etc/nginx/proxy.conf;
    }
  proxy.conf: |
    server {
      listen 8443 default;

      ssl on;
      ssl_certificate /etc/secrets/tls.crt;
      ssl_certificate_key /etc/secrets/tls.key;
      ssl_dhparam /etc/secrets/dhparam;

      ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
      ssl_ciphers ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-RSA-RC4-SHA:AES128-GCM-SHA256:HIGH:!RC4:!MD5:!aNULL:!EDH:!CAMELLIA;
      ssl_prefer_server_ciphers on;

      ssl_session_cache shared:SSL:10m;
      ssl_session_timeout 10m;

      add_header Strict-Transport-Security max-age=15638400;
      add_header X-Frame-Options DENY;
      add_header X-Content-Type-Options nosniff;

      location / {
          proxy_set_header        Host $host;
          proxy_set_header        X-Real-IP $remote_addr;
          proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header        X-Forwarded-Proto $scheme;
          proxy_set_header        X-Forwarded-Host $http_host;
          proxy_pass              http://localhost:8080;
          proxy_read_timeout      90;
          proxy_redirect          http:// https://;
          proxy_http_version      1.1;
      }
    }
