# oc apply -f /home/eace/go/nuxeo-operator/resources/deployment1-cr.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zzzzzz
  namespace: poc-rco
spec:
  selector:
    matchLabels:
      foo: bar
  template:
    metadata:
      labels:
        foo: bar
    spec:
      containers:
      - name: foo
        image: busybox