apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: proxy
subjects:
- kind: ServiceAccount
  name: nuxeo-operator-manager
  namespace: nuxeo-operator-system
