# permissions for end users to view nuxeos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nuxeo-viewer
rules:
- apiGroups:
  - nuxeo.appzygy.net
  resources:
  - nuxeos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nuxeo.appzygy.net
  resources:
  - nuxeos/status
  verbs:
  - get
