apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.0.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: nuxeo-operator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Nuxeo is the Schema for the nuxeos API
      displayName: Nuxeo
      kind: Nuxeo
      name: nuxeos.appzygy.net.appzygy.net
      version: v1alpha1
  description: The Nuxeo Operator manages a Nuxeo cluster and integrates it with backing services like Kafka,
    Elastic Search, MongoDB, and PostgreSQL.
  displayName: Nuxeo Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - nuxeo
  - digital
  - asset
  - management
  - kafka
  - elasticsearch
  - postgres
  - mongodb
  links:
  - name: Nuxeo Operator
    url: https://github.com/aceeric/nuxeo-operator
  maturity: alpha
  provider:
    name: Eric Ace
    url: https://github.com/aceeric/nuxeo-operator
  version: 0.0.0
