apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuxeo-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nuxeo-operator
  template:
    metadata:
      labels:
        name: nuxeo-operator
    spec:
      serviceAccountName: nuxeo-operator
      containers:
        - name: nuxeo-operator
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "nuxeo-operator"
