/*
Copyright 2020 Eric Ace.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Package nuxeo performs reconciliation for a Nuxeo custom resource and the objects that are generated by the Operator
from the CR: Deployment, Ingress/Route, Service, ServiceAccount, PVC, ConfigMap, & Secret.

Unit testing is performed using https://github.com/stretchr/testify. See the Make file for the unit test target.

Each unit test file conforms to the same structure:
  test functions - test functions are at the top, and take a test suite struct receiver
  suite struct - the test suite structure required by testify, and augmented with suite-specific state
  setup/teardown function(s) - perform setup / teardown
  suite function - is run by 'go test' and calls all test functions
  helper functions - called by the various test functions

The main "entry point" of the package is the Reconcile function in nuxeo_controller.go. Each dependent
resource is reconciled in a dedicated file. E.g. nuxeo_controller.go 'Reconcile' calls 'reconcileNodeSet' in
nodeset.go to reconcile the NodeSets in the Nuxeo CR. Same for Service, ServiceAccount, etc.
*/
package nuxeo
