apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: nuxeo-operator
  namespace: nuxeo-test
spec:
  targetNamespaces:
  - nuxeo-test
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: nuxeo-operator
  namespace: nuxeo-test
spec:
  channel: stable
  name: nuxeo-operator
  source: nuxeo-operator
  sourceNamespace: openshift-marketplace
