apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "nuxeo.com/v1alpha1",
          "kind": "Nuxeo",
          "metadata": {
            "name": "my-nuxeo"
          },
          "spec": {
            "access": {
              "hostname": "nuxeo-server.apps-crc.testing",
              "termination": "passthrough"
            },
            "nodeSets": [
              {
                "env": [
                  {
                    "name": "NUXEO_PACKAGES",
                    "value": "nuxeo-web-ui"
                  }
                ],
                "interactive": true,
                "name": "cluster",
                "replicas": 1
              }
            ],
            "nuxeoImage": "nuxeo:10.10",
            "revProxy": {
              "nginx": {
                "configMap": "tls-cfgmap",
                "image": "nginx:latest",
                "secret": "tls-secret"
              }
            }
          }
        },
        {
          "apiVersion": "nuxeo.com/v1alpha1",
          "kind": "Nuxeo",
          "metadata": {
            "name": "my-nuxeo"
          },
          "spec": {
            "access": {
              "hostname": "nuxeo-server.apps-crc.testing"
            },
            "nodeSets": [
              {
                "env": [
                  {
                    "name": "NUXEO_PACKAGES",
                    "value": "nuxeo-web-ui"
                  }
                ],
                "interactive": true,
                "name": "cluster",
                "replicas": 1
              }
            ],
            "nuxeoImage": "nuxeo:10.10"
          }
        }
      ]
    capabilities: Basic Install
  name: nuxeo-operator.v0.1.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Nuxeo is the Schema for the nuxeos API
      kind: Nuxeo
      name: nuxeos.nuxeo.com
      version: v1alpha1
  description: The Nuxeo Operator manages the state of a Nuxeo cluster.
  displayName: Nuxeo Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments:
      - name: nuxeo-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: nuxeo-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: nuxeo-operator
            spec:
              containers:
              - name: nuxeo-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: nuxeo-operator
                image: image-registry.openshift-image-registry.svc.cluster.local:5000/images/nuxeo-operator:0.1.0
                imagePullPolicy: Always
                resources:
                  limits:
                    cpu: 200m
                    memory: 128Mi
                  requests:
                    cpu: 100m
                    memory: 64Mi
              serviceAccountName: nuxeo-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - nuxeo-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - nuxeo.com
          resources:
          - nuxeos
          - nuxeos/status
          - nuxeos/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - extensions
          resources:
          - ingresses
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: nuxeo-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - nuxeo
  links:
  - name: Nuxeo product
    url: https://www.nuxeo.com/
  - name: Operator source code
    url: https://github.com/aceeric/nuxeo-operator
  maintainers:
  - name: Eric Ace
  maturity: alpha
  provider:
    name: Eric Ace
  version: 0.1.0
